print('Начало')
raise Exception('Что-то пошло не так... ;(')
print('Конец')
